package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Channel generated by hbm2java
 */
public class Channel  implements java.io.Serializable {


     private Integer idchannel;
     private Users users;
     private String name;
     private String details;
     private Date date;
     private Set<MdcOutlet> mdcOutlets = new HashSet<MdcOutlet>(0);

    public Channel() {
    }

	
    public Channel(Users users, String name, String details, Date date) {
        this.users = users;
        this.name = name;
        this.details = details;
        this.date = date;
    }
    public Channel(Users users, String name, String details, Date date, Set<MdcOutlet> mdcOutlets) {
       this.users = users;
       this.name = name;
       this.details = details;
       this.date = date;
       this.mdcOutlets = mdcOutlets;
    }
   
    public Integer getIdchannel() {
        return this.idchannel;
    }
    
    public void setIdchannel(Integer idchannel) {
        this.idchannel = idchannel;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<MdcOutlet> getMdcOutlets() {
        return this.mdcOutlets;
    }
    
    public void setMdcOutlets(Set<MdcOutlet> mdcOutlets) {
        this.mdcOutlets = mdcOutlets;
    }




}


