package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DcOwner generated by hbm2java
 */
public class DcOwner  implements java.io.Serializable {


     private Integer iddcOwner;
     private Users users;
     private String name;
     private int telephone;
     private String email;
     private Date date;
     private Set<DcInfo> dcInfos = new HashSet<DcInfo>(0);

    public DcOwner() {
    }

	
    public DcOwner(Users users, String name, int telephone, String email, Date date) {
        this.users = users;
        this.name = name;
        this.telephone = telephone;
        this.email = email;
        this.date = date;
    }
    public DcOwner(Users users, String name, int telephone, String email, Date date, Set<DcInfo> dcInfos) {
       this.users = users;
       this.name = name;
       this.telephone = telephone;
       this.email = email;
       this.date = date;
       this.dcInfos = dcInfos;
    }
   
    public Integer getIddcOwner() {
        return this.iddcOwner;
    }
    
    public void setIddcOwner(Integer iddcOwner) {
        this.iddcOwner = iddcOwner;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(int telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<DcInfo> getDcInfos() {
        return this.dcInfos;
    }
    
    public void setDcInfos(Set<DcInfo> dcInfos) {
        this.dcInfos = dcInfos;
    }




}


