package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DeliveredItem generated by hbm2java
 */
public class DeliveredItem  implements java.io.Serializable {


     private Integer iddeliveredItem;
     private ProductType productType;
     private Assets assets;
     private Users users;
     private int quantity;
     private Date date;

    public DeliveredItem() {
    }

    public DeliveredItem(ProductType productType, Assets assets, Users users, int quantity, Date date) {
       this.productType = productType;
       this.assets = assets;
       this.users = users;
       this.quantity = quantity;
       this.date = date;
    }
   
    public Integer getIddeliveredItem() {
        return this.iddeliveredItem;
    }
    
    public void setIddeliveredItem(Integer iddeliveredItem) {
        this.iddeliveredItem = iddeliveredItem;
    }
    public ProductType getProductType() {
        return this.productType;
    }
    
    public void setProductType(ProductType productType) {
        this.productType = productType;
    }
    public Assets getAssets() {
        return this.assets;
    }
    
    public void setAssets(Assets assets) {
        this.assets = assets;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


