package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer iddelivery;
     private Outlet outlet;
     private Tracks tracks;
     private Users users;
     private String details;
     private Date date;

    public Delivery() {
    }

    public Delivery(Outlet outlet, Tracks tracks, Users users, String details, Date date) {
       this.outlet = outlet;
       this.tracks = tracks;
       this.users = users;
       this.details = details;
       this.date = date;
    }
   
    public Integer getIddelivery() {
        return this.iddelivery;
    }
    
    public void setIddelivery(Integer iddelivery) {
        this.iddelivery = iddelivery;
    }
    public Outlet getOutlet() {
        return this.outlet;
    }
    
    public void setOutlet(Outlet outlet) {
        this.outlet = outlet;
    }
    public Tracks getTracks() {
        return this.tracks;
    }
    
    public void setTracks(Tracks tracks) {
        this.tracks = tracks;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


