package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ProductPackage generated by hbm2java
 */
public class ProductPackage  implements java.io.Serializable {


     private Integer idproductPackage;
     private ProductType productType;
     private Users users;
     private String name;
     private Date date;

    public ProductPackage() {
    }

    public ProductPackage(ProductType productType, Users users, String name, Date date) {
       this.productType = productType;
       this.users = users;
       this.name = name;
       this.date = date;
    }
   
    public Integer getIdproductPackage() {
        return this.idproductPackage;
    }
    
    public void setIdproductPackage(Integer idproductPackage) {
        this.idproductPackage = idproductPackage;
    }
    public ProductType getProductType() {
        return this.productType;
    }
    
    public void setProductType(ProductType productType) {
        this.productType = productType;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


