package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductType generated by hbm2java
 */
public class ProductType  implements java.io.Serializable {


     private Integer idproductType;
     private Users users;
     private String name;
     private String details;
     private Date datetime;
     private Set<StockControl> stockControls = new HashSet<StockControl>(0);
     private Set<ProductPackage> productPackages = new HashSet<ProductPackage>(0);
     private Set<ProductSize> productSizes = new HashSet<ProductSize>(0);
     private Set<DeliveredItem> deliveredItems = new HashSet<DeliveredItem>(0);

    public ProductType() {
    }

	
    public ProductType(Users users, String name, String details, Date datetime) {
        this.users = users;
        this.name = name;
        this.details = details;
        this.datetime = datetime;
    }
    public ProductType(Users users, String name, String details, Date datetime, Set<StockControl> stockControls, Set<ProductPackage> productPackages, Set<ProductSize> productSizes, Set<DeliveredItem> deliveredItems) {
       this.users = users;
       this.name = name;
       this.details = details;
       this.datetime = datetime;
       this.stockControls = stockControls;
       this.productPackages = productPackages;
       this.productSizes = productSizes;
       this.deliveredItems = deliveredItems;
    }
   
    public Integer getIdproductType() {
        return this.idproductType;
    }
    
    public void setIdproductType(Integer idproductType) {
        this.idproductType = idproductType;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Set<StockControl> getStockControls() {
        return this.stockControls;
    }
    
    public void setStockControls(Set<StockControl> stockControls) {
        this.stockControls = stockControls;
    }
    public Set<ProductPackage> getProductPackages() {
        return this.productPackages;
    }
    
    public void setProductPackages(Set<ProductPackage> productPackages) {
        this.productPackages = productPackages;
    }
    public Set<ProductSize> getProductSizes() {
        return this.productSizes;
    }
    
    public void setProductSizes(Set<ProductSize> productSizes) {
        this.productSizes = productSizes;
    }
    public Set<DeliveredItem> getDeliveredItems() {
        return this.deliveredItems;
    }
    
    public void setDeliveredItems(Set<DeliveredItem> deliveredItems) {
        this.deliveredItems = deliveredItems;
    }




}


