package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ProductSize generated by hbm2java
 */
public class ProductSize  implements java.io.Serializable {


     private Integer idproductSize;
     private ProductType productType;
     private Users users;
     private int quantity;
     private Date date;

    public ProductSize() {
    }

    public ProductSize(ProductType productType, Users users, int quantity, Date date) {
       this.productType = productType;
       this.users = users;
       this.quantity = quantity;
       this.date = date;
    }
   
    public Integer getIdproductSize() {
        return this.idproductSize;
    }
    
    public void setIdproductSize(Integer idproductSize) {
        this.idproductSize = idproductSize;
    }
    public ProductType getProductType() {
        return this.productType;
    }
    
    public void setProductType(ProductType productType) {
        this.productType = productType;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


