package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA



/**
 * QuantityTypes generated by hbm2java
 */
public class QuantityTypes  implements java.io.Serializable {


     private Integer idquantityTypes;
     private Users users;
     private int unit;
     private String details;
     private String date;

    public QuantityTypes() {
    }

    public QuantityTypes(Users users, int unit, String details, String date) {
       this.users = users;
       this.unit = unit;
       this.details = details;
       this.date = date;
    }
   
    public Integer getIdquantityTypes() {
        return this.idquantityTypes;
    }
    
    public void setIdquantityTypes(Integer idquantityTypes) {
        this.idquantityTypes = idquantityTypes;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getUnit() {
        return this.unit;
    }
    
    public void setUnit(int unit) {
        this.unit = unit;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


