package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RedCardScore generated by hbm2java
 */
public class RedCardScore  implements java.io.Serializable {


     private Integer idredCardScore;
     private Users users;
     private int quantityTypeId;
     private int score;
     private String details;
     private int productTypeId;
     private Date date;

    public RedCardScore() {
    }

    public RedCardScore(Users users, int quantityTypeId, int score, String details, int productTypeId, Date date) {
       this.users = users;
       this.quantityTypeId = quantityTypeId;
       this.score = score;
       this.details = details;
       this.productTypeId = productTypeId;
       this.date = date;
    }
   
    public Integer getIdredCardScore() {
        return this.idredCardScore;
    }
    
    public void setIdredCardScore(Integer idredCardScore) {
        this.idredCardScore = idredCardScore;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getQuantityTypeId() {
        return this.quantityTypeId;
    }
    
    public void setQuantityTypeId(int quantityTypeId) {
        this.quantityTypeId = quantityTypeId;
    }
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public int getProductTypeId() {
        return this.productTypeId;
    }
    
    public void setProductTypeId(int productTypeId) {
        this.productTypeId = productTypeId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


