package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RedClass generated by hbm2java
 */
public class RedClass  implements java.io.Serializable {


     private Integer idredClass;
     private Users users;
     private String name;
     private String details;
     private Set<MdcOutlet> mdcOutlets = new HashSet<MdcOutlet>(0);

    public RedClass() {
    }

	
    public RedClass(Users users, String name, String details) {
        this.users = users;
        this.name = name;
        this.details = details;
    }
    public RedClass(Users users, String name, String details, Set<MdcOutlet> mdcOutlets) {
       this.users = users;
       this.name = name;
       this.details = details;
       this.mdcOutlets = mdcOutlets;
    }
   
    public Integer getIdredClass() {
        return this.idredClass;
    }
    
    public void setIdredClass(Integer idredClass) {
        this.idredClass = idredClass;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Set<MdcOutlet> getMdcOutlets() {
        return this.mdcOutlets;
    }
    
    public void setMdcOutlets(Set<MdcOutlet> mdcOutlets) {
        this.mdcOutlets = mdcOutlets;
    }




}


