package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Routes generated by hbm2java
 */
public class Routes  implements java.io.Serializable {


     private Integer idroutes;
     private Users users;
     private String name;
     private String area;
     private String region;
     private String details;
     private Date date;
     private Set<Outlet> outlets = new HashSet<Outlet>(0);
     private Set<MdcOutlet> mdcOutlets = new HashSet<MdcOutlet>(0);

    public Routes() {
    }

	
    public Routes(Users users, String name, String area, String region, String details, Date date) {
        this.users = users;
        this.name = name;
        this.area = area;
        this.region = region;
        this.details = details;
        this.date = date;
    }
    public Routes(Users users, String name, String area, String region, String details, Date date, Set<Outlet> outlets, Set<MdcOutlet> mdcOutlets) {
       this.users = users;
       this.name = name;
       this.area = area;
       this.region = region;
       this.details = details;
       this.date = date;
       this.outlets = outlets;
       this.mdcOutlets = mdcOutlets;
    }
   
    public Integer getIdroutes() {
        return this.idroutes;
    }
    
    public void setIdroutes(Integer idroutes) {
        this.idroutes = idroutes;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<Outlet> getOutlets() {
        return this.outlets;
    }
    
    public void setOutlets(Set<Outlet> outlets) {
        this.outlets = outlets;
    }
    public Set<MdcOutlet> getMdcOutlets() {
        return this.mdcOutlets;
    }
    
    public void setMdcOutlets(Set<MdcOutlet> mdcOutlets) {
        this.mdcOutlets = mdcOutlets;
    }




}


