package model;
// Generated Mar 29, 2013 3:29:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tracks generated by hbm2java
 */
public class Tracks  implements java.io.Serializable {


     private Integer idtracks;
     private Users users;
     private String number;
     private String plate;
     private String details;
     private Date date;
     private Set<Delivery> deliveries = new HashSet<Delivery>(0);

    public Tracks() {
    }

	
    public Tracks(Users users, String number, String plate, String details, Date date) {
        this.users = users;
        this.number = number;
        this.plate = plate;
        this.details = details;
        this.date = date;
    }
    public Tracks(Users users, String number, String plate, String details, Date date, Set<Delivery> deliveries) {
       this.users = users;
       this.number = number;
       this.plate = plate;
       this.details = details;
       this.date = date;
       this.deliveries = deliveries;
    }
   
    public Integer getIdtracks() {
        return this.idtracks;
    }
    
    public void setIdtracks(Integer idtracks) {
        this.idtracks = idtracks;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getPlate() {
        return this.plate;
    }
    
    public void setPlate(String plate) {
        this.plate = plate;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<Delivery> getDeliveries() {
        return this.deliveries;
    }
    
    public void setDeliveries(Set<Delivery> deliveries) {
        this.deliveries = deliveries;
    }




}


